substitutions:
  _IMAGE: 'asia-southeast1-docker.pkg.dev/${PROJECT_ID}/ghostfolio/ghostfolio:latest'

steps:
  # Pull the previous image to use as cache
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - 'docker pull ${_IMAGE} || exit 0'

  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        '${_IMAGE}',
        '--cache-from',
        '${_IMAGE}',
        '--build-arg',
        'BUILDKIT_INLINE_CACHE=1',
        '.'
      ]
    env:
      - 'DOCKER_BUILDKIT=1'

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_IMAGE}']

  # Trigger GKE Rollout
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud container clusters get-credentials ${_GKE_CLUSTER_NAME} \
          --region=${_GKE_REGION} \
          --project=${_GKE_PROJECT_ID}

        kubectl rollout restart deployment ghostfolio -n ghostfolio

images:
  - '${_IMAGE}'

options:
  logging: CLOUD_LOGGING_ONLY
